apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: nssbuto-f-go 
  janus-idp.io/tekton: nssbuto-f-go
  backstage.io/kubernetes-id: nssbuto-f-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nssbuto-f-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  